plugin_type:
  source:
  - netbox-Rome:
    plugin_name: netbox
    args: 
      token: "0123456789abcdef0123456789abcdef01234567"
      ip_address: "127.0.0.1"
      protocol: "http"
      port: "8000"
poller_config:
  ...
provider_config:
  period: 60
  ...
  