inventory_provider:
  plugin_type:
    source:
    - local-netbox:
      plugin_name: netbox
      args:
        credentials:
          token: "0123456789abcdef0123456789abcdef01234567"
        ip_address: "127.0.0.1"
        use_https: false
        port: "8000"
        namespace: "local"
        tag: "suzieq"
        period: 3
        devices_credentials:
          file_path: "./local-netbox-devices-credentials.yaml"
    - remote-netbox-demo:
      plugin_name: netbox
      args:
        credentials:
          token: "05890d9066e2e89eeffee766f579832388547786"
        ip_address: "demo.netbox.dev"
        use_https: true
        port: "443"
        period: 5
        tag: "test-tag"
        devices_credentials:
          file_path: "./remote-netbox-demo-devices-credentials.yaml"
#   pollerManager:
#     ...
#   chunker:
#     ...
# provider_config:
#   period: 60
#   ...
    